name: Fetch Bedrock Block Mapping
on: pull_request
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p mapping
          curl -L --fail --silent --show-error https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v3.1/java-to-bedrock.json -o mapping/java-to-bedrock.json
          curl -L --fail --silent --show-error https://raw.githubusercontent.com/platz1de/EasyEdit-Data/format-v3.1/bedrock-defaults.json -o mapping/bedrock-defaults.json
          sha256sum mapping/* > mapping/SHA256.txt
      - uses: actions/upload-artifact@v4
        with:
          name: bedrock-block-mapping
          path: mapping/
          retention-days: 1
